version: "3.9"

services:

  nginx:
    image: nginx:latest
    #container_name: app_nginx_fpm
    ports:
      - "8080:80"
    volumes:
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./:/var/www/
    depends_on:
      - app
    container_name: project_nginx

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile

    #container_name: app_php
    volumes:
      - ./:/var/www/
    container_name: project_app
