version: "3.9"

services:

  nginx:
    image: nginx:latest
    #container_name: app_nginx_fpm
    ports:
      - "8080:80"
    volumes:
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./:/var/www/
    depends_on:
      - app
    container_name: project_nginx

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile

    #container_name: app_php
    volumes:
      - ./:/var/www/
    container_name: project_app

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql #//This means: The database is stored on disk,  Will not be lost when docker-compose down
    environment:
      #The lardocker database and root password will be created.
      MYSQL_DATABASE: lardocker
      MYSQL_ROOT_PASSWORD: root
    ports:
    #8101 → port on your PC, 3306 → port inside the container
      - "8101:3306"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: project_db

